Add `prism` parser support
The `prism` get is temporary pointed to the main since `Prism::Translation::ParserCurrent`
is not yet releases. Let me know if we want to support prism 1.4.

When using prism the following specs are failing:

```
Failures:

  1) Unparser corpus passes the semantic corpus
     Failure/Error: expect(Unparser::CLI.run(%w[test/corpus/semantic] + version_excludes)).to be(0)

       expected #<Integer:1> => 0
            got #<Integer:3> => 1

       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     # ./spec/unit/unparser_spec.rb:486:in 'block (3 levels) in <top (required)>'

  2) Unparser corpus passes the literal corpus
     Failure/Error: expect(Unparser::CLI.run(%w[test/corpus/literal --literal] + version_excludes)).to be(0)

       expected #<Integer:1> => 0
            got #<Integer:3> => 1

       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     # ./spec/unit/unparser_spec.rb:482:in 'block (3 levels) in <top (required)>'

Finished in 0.39694 seconds (files took 0.32491 seconds to load)
509 examples, 2 failures

Failed examples:

rspec ./spec/unit/unparser_spec.rb:485 # Unparser corpus passes the semantic corpus
rspec ./spec/unit/unparser_spec.rb:481 # Unparser corpus passes the literal corpus
```

It might be a bug (at least one of the failures) in the prism itself:

```bash
$ cat /tmp/prism.rb
ruby = <<~RUBY
  begin
    raise '42'
  rescue => A[]
  end
RUBY

require "prism"
raise unless Prism::VERSION == '1.4.0'

Prism::Translation::Parser.parse(ruby).value.accept(Prism::Compiler.new)

$ env ASDF_RUBY_VERSION=3.4.2 ruby /tmp/prism.rb
prism-1.4.0/lib/prism/translation/parser/compiler.rb:1059:in `visit_index_target_node': undefined method `arguments' for nil (NoMethodError)

            visit_all(node.arguments.arguments),
                                    ^^^^^^^^^^
prism-1.4.0/lib/prism/node.rb:9636:in `accept'
prism-1.4.0/lib/prism/compiler.rb:30:in `visit'
prism-1.4.0/lib/prism/translation/parser/compiler.rb:226:in `visit_begin_node'
```